[package]
name = "kid-end2end"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

# No lib — this crate only contains integration tests.

[dev-dependencies]
anyhow.workspace = true
cucumber = "0.21"
fantoccini = "0.21"
pretty_assertions = "1.4"
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[[test]]
name = "app_suite"
harness = false    # Cucumber controls output instead of libtest
