[package]
name = "kid-end2end"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dev-dependencies]
anyhow.workspace = true
assert_fs.workspace = true
base64.workspace = true
chrono.workspace = true
cucumber = "0.21"
indexmap.workspace = true
kid-types = { path = "../types" }
reqwest = { version = "0.13", features = ["json", "form"] }
rmcp = { workspace = true, features = ["client", "transport-streamable-http-client-reqwest"] }
serde_json.workspace = true
sha2.workspace = true
strum.workspace = true
thirtyfour = "0.37.0"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
url.workspace = true
uuid = { workspace = true, features = ["v4", "v7"] }

[[test]]
name = "browser"
harness = false # allows Cucumber to print output instead of libtest
