[package]
name = "kid-types"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
default = []
rpc = ["dep:tarpc"]
ssr = [
  "rpc",
  "chrono/now",
  "uuid/rng-rand",
  "uuid/v7",
  "dep:indexmap",
  "dep:ahash",
  "dep:tokio",
  "dep:serde_json",
]
ssr-test = ["dep:rand"]

[dependencies]
ahash = { workspace = true, optional = true }
cfg-if.workspace = true
chrono = { workspace = true, features = ["std", "serde"] }
derive_more = { workspace = true, features = ["display"] }
indexmap = { workspace = true, optional = true }
miette = { version = "7.6.0", features = ["fancy", "fancy-base"] }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["indexmap", "preserve_order"], optional = true }
tarpc = { workspace = true, features = ["serde1"], optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["fs"], optional = true }
tracing.workspace = true
uuid = { workspace = true, features = ["serde"] }

[dev-dependencies]
assert_fs.workspace = true
predicates.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tracing-test.workspace = true
