[package]
name = "kid-types"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[features]
default = []
rpc = ["dep:tarpc"]
ssr = ["rpc", "uuid/rng-rand", "uuid/v7", "dep:indexmap", "dep:ahash"]

[dependencies]
ahash = { workspace = true, optional = true }
indexmap = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
tarpc = { workspace = true, features = ["serde1"], optional = true }
uuid = { workspace = true, features = ["serde"] }
