[package]
name = "kid-service"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
rand.workspace = true
tarpc = { workspace = true, features = ["full"] }
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "tokio-macros",
] }
tracing.workspace = true
