[package]
name = "kid-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "kid_cli"
path = "src/lib.rs"

[[bin]]
name = "kid"
path = "src/main.rs"

[lints]
workspace = true

[dependencies.kid-types]
path = "../types"
features = ["cli"]

[dependencies]
clap = { workspace = true, features = ["env"] }
indexmap.workspace = true
clap-verbosity-flag.workspace = true
miette = { workspace = true, features = ["fancy"] }
schemars.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sublime_fuzzy.workspace = true
tarpc = { workspace = true, features = ["full"] }
thiserror.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "tokio-macros",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
