[package]
name = "kid-server"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "kiddy"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap-verbosity-flag.workspace = true
futures.workspace = true
kid-service = { path = "../service" }
kid-types = { path = "../types" }
rand.workspace = true
tarpc = { workspace = true, features = ["full"] }
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "tokio-macros",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
