[package]
name = "kid-server"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies.kid-types]
path = "../types"

[dependencies.kid-app]
path = "../app"
default-features = false
features = ["ssr"]

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap = { workspace = true, features = ["env"] }
clap-verbosity-flag.workspace = true
futures.workspace = true
indexmap.workspace = true
leptos = { workspace = true, features = ["ssr"] }
leptos_axum.workspace = true
miette = { workspace = true, features = ["fancy"] }
rand.workspace = true
serde_json.workspace = true
tarpc = { workspace = true, features = ["full"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tokio-util.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
